CREATE TABLE IF NOT EXISTS rewards (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    match_id INT NOT NULL,
    user_id INT NOT NULL,
    amount DOUBLE NOT NULL,
    win TINYINT NOT NULL DEFAULT 1,
    email_sent TINYINT NOT NULL DEFAULT 0
);